export const EMPLOYEE_STATUS = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  ON_LEAVE: "ON_LEAVE",
}

export const EMPLOYEE_STATUS_BADGE_VARIANT = {
  [EMPLOYEE_STATUS.ACTIVE]: "green",
  [EMPLOYEE_STATUS.INACTIVE]: "gray",
  [EMPLOYEE_STATUS.ON_LEAVE]: "yellow",
}
